### ISSUE TITLE
Oppdatere nuget project url

### ISSUE THREAD

**Issue by Destidom** [difi/dpi-proxy-klient-dotnet#8]
Heisann

Burde ikke denne URLen lenke til det faktiske prosjektet "dpi-proxy-klient-dotnet" istedenfor "sikker-digital-post-klient-dotnet"?

ref:
https://github.com/difi/dpi-proxy-klient-dotnet/blob/44ab1c46cecf818326d7673ad07009eda1181a0a/Directory.Build.props#L12

**Comment by johnksv** [comment]
Hei, det stemmer, det burde den.
